#!/usr/bin/env python3
"""Render the README Quickstart section from a live run of the engine.

WHY THIS EXISTS
---------------
cdfi-stress-tester 0.1.0 shipped a hand-transcribed README quickstart whose every
figure was wrong and whose capital-adequacy verdict was REVERSED: the README showed
"CAR 2.14x / STATUS: ADEQUATE" where the code actually prints "0.57x / INSUFFICIENT".
On a package sold for CDFI Fund reporting and rating-agency submissions, that is the
worst possible defect.

So the README quickstart is no longer written by hand.  It is a COMMITTED ARTIFACT
generated by this script.  This module owns the quickstart SOURCE as well as its
OUTPUT and emits both into README.md between generated-region markers, which means
the two provably came from the same execution -- the snippet in the README cannot
drift away from the numbers printed underneath it.

``tests/test_readme_artifact.py`` re-runs this renderer and byte-diffs the result
against what is committed, so CI fails if README.md and the code ever disagree.

USAGE
-----
    python scripts/render_readme_block.py            # rewrite README.md in place
    python scripts/render_readme_block.py --check    # exit 1 if README.md is stale
"""
from __future__ import annotations

import argparse
import contextlib
import difflib
import io
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"

BEGIN_MARK = "<!-- BEGIN GENERATED: quickstart (scripts/render_readme_block.py) -->"
END_MARK = "<!-- END GENERATED: quickstart -->"

# The quickstart itself.  This string is BOTH what the README displays and what is
# executed to produce the output the README displays.  Keep it copy-pasteable.
QUICKSTART_SOURCE = '''\
from cdfistress import (
    generate_sample_portfolio,
    from_standard,
    MonteCarloEngine,
    generate_stress_report,
    scenario_comparison_table,
    capital_adequacy_report,
)

# A reproducible 50-loan CDFI portfolio
loans = generate_sample_portfolio(n=50, seed=42)

# Monte Carlo engine with $5MM of loss-absorbing capital
engine = MonteCarloEngine(loans=loans, available_capital=5_000_000)

# Run a 2008-style recession
result = engine.run_simulation(from_standard("2008_recession"), n_iterations=1000, seed=42)
print(generate_stress_report(result))

# Capital adequacy against the loss distribution that run produced
print()
for key, value in capital_adequacy_report(5_000_000, engine.loss_distribution).items():
    print(f"  {key:<18} {value:>18,.4f}")

# Inspect a scenario's parameters
print()
print(from_standard("rate_spike").summary())

# Compare several scenarios side by side
scenarios = [from_standard(k) for k in ["mild_downturn", "rate_spike", "2008_recession"]]
results = [engine.run_simulation(s, n_iterations=500, seed=0) for s in scenarios]
print()
print(scenario_comparison_table(results))
'''


def run_quickstart() -> str:
    """Execute QUICKSTART_SOURCE against the working tree and capture its stdout."""
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        exec(compile(QUICKSTART_SOURCE, "<quickstart>", "exec"), {"__name__": "__quickstart__"})
    return buf.getvalue()


def render_region() -> str:
    """Return the full generated README region, markers included."""
    output = run_quickstart().rstrip("\n")
    return (
        f"{BEGIN_MARK}\n"
        f"<!-- Do not edit by hand.  Regenerate: python scripts/render_readme_block.py -->\n"
        f"\n"
        f"```python\n"
        f"{QUICKSTART_SOURCE.rstrip()}\n"
        f"```\n"
        f"\n"
        f"Output (verbatim -- this block is generated by executing the snippet above):\n"
        f"\n"
        f"```text\n"
        f"{output}\n"
        f"```\n"
        f"\n"
        f"{END_MARK}"
    )


def split_readme(text: str):
    """Split README into (before, current_region, after).  Raises if markers are bad."""
    if text.count(BEGIN_MARK) != 1 or text.count(END_MARK) != 1:
        raise SystemExit(
            f"README.md must contain exactly one {BEGIN_MARK} and one {END_MARK} "
            f"(found {text.count(BEGIN_MARK)} and {text.count(END_MARK)})"
        )
    start = text.index(BEGIN_MARK)
    end = text.index(END_MARK) + len(END_MARK)
    if end < start:
        raise SystemExit("README.md generated-region markers are out of order")
    return text[:start], text[start:end], text[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if README.md does not match a fresh render",
    )
    args = parser.parse_args()

    text = README.read_text(encoding="utf-8")
    before, current, after = split_readme(text)
    fresh = render_region()

    if current == fresh:
        print("README.md quickstart is up to date.")
        return 0

    if args.check:
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            fresh.splitlines(keepends=True),
            fromfile="README.md (committed)",
            tofile="README.md (freshly rendered)",
        )
        sys.stdout.writelines(diff)
        print("\nREADME.md is STALE. Regenerate: python scripts/render_readme_block.py")
        return 1

    README.write_text(before + fresh + after, encoding="utf-8")
    print("README.md quickstart regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
